### ISSUE TITLE
Unable to access Admin page

### ISSUE THREAD

**Issue by blockChn** [ProofOfToss/proof-of-toss#1]
I have followed the installation instructions, the site is up with local testnet running.
But, I am not able to see and bets, create new bet.
How to access Admin page to create bets ?

**Comment by epavlenko** [comment]
Hi asifzuddin. You can create events in admin page. As it is written in README.md in "How to install" section point number 8:
> For accessing admin pages account must be whitelisted. Whitelist is located at src/data/config.json Add address from 4 step to the whitelist key. To synchronize white list with blockchain run:
> $ npm run sync_whitelist
> It should be executed after each deploy.

**Comment by blockChn** [comment]
Thanks for your reply, I am not able to access the Admin page. It is not coming up when I login.
I have followed the read me to white list the accounts also.
Anything else need to be done ?

**Comment by blockChn** [comment]
got it right. thanks
